/**
 * The statements that seeded this import, as it made them on the day it was
 * written: `20260914_222809_publish_referral_signup_wording` (ticket 68).
 *
 * **Generated, and frozen.** `npm run cms:freeze-seed` produced this from the
 * import as it ran, and nothing regenerates it: the column names below are the
 * ones these tables had at that point in the chain, which is the whole point of
 * the file. A field added to this entry later belongs in a migration of its
 * own, never here.
 *
 * The words themselves are in `words.ts` beside this, which is what to read.
 */
export const REFERRAL_SIGNUP_SEED = `
INSERT INTO "_referral_signup_form_v" ("id", "version_alert_address", "version_heading", "version_lead", "version_submit", "version_fine_print", "version_fields_name_label", "version_fields_name_placeholder", "version_fields_name_message", "version_fields_phone_label", "version_fields_phone_placeholder", "version_fields_phone_message", "version_fields_email_label", "version_fields_email_placeholder", "version_fields_email_message", "version_fields_city_label", "version_fields_city_placeholder", "version_fields_city_message", "version_fields_profession_label", "version_fields_profession_placeholder", "version_fields_profession_message", "version_fields_profession_options_option_engineer", "version_fields_profession_options_option_project_manager", "version_fields_profession_options_option_independent_consultant", "version_fields_profession_options_option_contractor", "version_fields_profession_options_option_real_estate_advisor", "version_fields_profession_options_option_content_creator", "version_fields_profession_options_option_other", "version_fields_employer_label", "version_fields_employer_placeholder", "version_fields_employer_message", "version_fields_iban_certificate_label", "version_fields_iban_certificate_placeholder", "version_fields_iban_certificate_message", "version_fields_iban_certificate_too_large", "version_fields_iban_certificate_wrong_type", "version_fields_account_holder_label", "version_fields_account_holder_placeholder", "version_fields_account_holder_message", "version_fields_commercial_registration_label", "version_fields_commercial_registration_placeholder", "version_fields_commercial_registration_message", "version_fields_commercial_registration_too_large", "version_fields_commercial_registration_wrong_type", "version_fields_tax_registration_certificate_label", "version_fields_tax_registration_certificate_placeholder", "version_fields_tax_registration_certificate_message", "version_fields_tax_registration_certificate_too_large", "version_fields_tax_registration_certificate_wrong_type", "version_fields_accept_terms_label", "version_fields_accept_terms_message", "version_fields_declare_no_conflict_label", "version_fields_declare_no_conflict_message", "version_received", "version_refused", "version_failed", "version_confirmation_subject", "version_confirmation_body", "version__status", "version_updated_at", "version_created_at", "created_at", "updated_at", "latest")
VALUES ('1', NULL, 'سجّل في برنامج الإحالة', 'البيانات والمستندات تُستخدم لإصدار كودك وتحويل مستحقاتك فقط.', 'سجّل في برنامج الإحالة', 'تُحفظ مستنداتك في مساحة خاصة لا يصل إليها إلا فريق ربائد، ولا تُستخدم إلا لإصدار كودك وتحويل مستحقاتك.', 'الاسم الكامل', 'الاسم الكامل *', 'اكتب اسمك الكامل (حرفان على الأقل)', 'رقم الجوال', 'رقم الجوال *', 'اكتب رقم جوال صحيح (٦ إلى ١٥ رقماً)', 'البريد الإلكتروني', 'البريد الإلكتروني *', 'اكتب بريداً إلكترونياً صحيحاً', 'المدينة', 'المدينة *', 'اكتب اسم مدينتك', 'الصفة المهنية', 'الصفة المهنية *', 'اختر صفتك المهنية', 'مهندس', 'مدير مشروع', 'استشاري مستقل', 'مقاول', 'مستشار تطوير عقاري', 'صانع محتوى', 'أخرى', 'جهة العمل', 'جهة العمل (اختياري)', 'اسم جهة العمل أطول من اللازم', 'شهادة الآيبان', 'PDF أو صورة', 'أرفق شهادة الآيبان', 'الملف أكبر من 10 ميجابايت — اختر ملفاً أصغر', 'ارفع ملف PDF أو صورة PNG أو JPG', 'اسم صاحب الحساب البنكي', 'اسم صاحب الحساب البنكي *', 'اكتب اسم صاحب الحساب كما في شهادة الآيبان', 'السجل التجاري', 'اختياري · PDF أو صورة', 'أرفق السجل التجاري', 'الملف أكبر من 10 ميجابايت — اختر ملفاً أصغر', 'ارفع ملف PDF أو صورة PNG أو JPG', 'شهادة التسجيل الضريبي', 'اختياري · PDF أو صورة', 'أرفق شهادة التسجيل الضريبي', 'الملف أكبر من 10 ميجابايت — اختر ملفاً أصغر', 'ارفع ملف PDF أو صورة PNG أو JPG', 'الموافقة على الشروط والأحكام', 'يلزم الموافقة على الشروط والأحكام وسياسة الخصوصية', 'إقرار عدم التعارض', 'يلزم الإقرار بعدم التعارض', 'وصلنا تسجيلك — سنراجع بياناتك ومستنداتك ونتواصل معك لإصدار كودك.', 'تعذّر استلام تسجيلك الآن. حاول مرة أخرى بعد قليل، أو راسلنا على واتساب.', 'لم يُحفظ تسجيلك بسبب خطأ من جهتنا. حاول مرة أخرى بعد قليل، أو راسلنا على واتساب.', 'ربائد — وصلنا تسجيلك في برنامج الإحالة', 'مرحباً {الاسم}،

وصلنا تسجيلك في برنامج الإحالة. سيراجع فريقنا بياناتك ومستنداتك، ونتواصل معك لإصدار كودك.

فريق ربائد', 'published', now(), now(), now(), now(), 'true');

SELECT setval(pg_get_serial_sequence('"_referral_signup_form_v"', 'id'), (SELECT max("id") FROM "_referral_signup_form_v"));

INSERT INTO "referral_signup_form" ("id", "alert_address", "heading", "lead", "submit", "fine_print", "fields_name_label", "fields_name_placeholder", "fields_name_message", "fields_phone_label", "fields_phone_placeholder", "fields_phone_message", "fields_email_label", "fields_email_placeholder", "fields_email_message", "fields_city_label", "fields_city_placeholder", "fields_city_message", "fields_profession_label", "fields_profession_placeholder", "fields_profession_message", "fields_profession_options_option_engineer", "fields_profession_options_option_project_manager", "fields_profession_options_option_independent_consultant", "fields_profession_options_option_contractor", "fields_profession_options_option_real_estate_advisor", "fields_profession_options_option_content_creator", "fields_profession_options_option_other", "fields_employer_label", "fields_employer_placeholder", "fields_employer_message", "fields_iban_certificate_label", "fields_iban_certificate_placeholder", "fields_iban_certificate_message", "fields_iban_certificate_too_large", "fields_iban_certificate_wrong_type", "fields_account_holder_label", "fields_account_holder_placeholder", "fields_account_holder_message", "fields_commercial_registration_label", "fields_commercial_registration_placeholder", "fields_commercial_registration_message", "fields_commercial_registration_too_large", "fields_commercial_registration_wrong_type", "fields_tax_registration_certificate_label", "fields_tax_registration_certificate_placeholder", "fields_tax_registration_certificate_message", "fields_tax_registration_certificate_too_large", "fields_tax_registration_certificate_wrong_type", "fields_accept_terms_label", "fields_accept_terms_message", "fields_declare_no_conflict_label", "fields_declare_no_conflict_message", "received", "refused", "failed", "confirmation_subject", "confirmation_body", "_status", "updated_at", "created_at")
VALUES ('1', NULL, 'سجّل في برنامج الإحالة', 'البيانات والمستندات تُستخدم لإصدار كودك وتحويل مستحقاتك فقط.', 'سجّل في برنامج الإحالة', 'تُحفظ مستنداتك في مساحة خاصة لا يصل إليها إلا فريق ربائد، ولا تُستخدم إلا لإصدار كودك وتحويل مستحقاتك.', 'الاسم الكامل', 'الاسم الكامل *', 'اكتب اسمك الكامل (حرفان على الأقل)', 'رقم الجوال', 'رقم الجوال *', 'اكتب رقم جوال صحيح (٦ إلى ١٥ رقماً)', 'البريد الإلكتروني', 'البريد الإلكتروني *', 'اكتب بريداً إلكترونياً صحيحاً', 'المدينة', 'المدينة *', 'اكتب اسم مدينتك', 'الصفة المهنية', 'الصفة المهنية *', 'اختر صفتك المهنية', 'مهندس', 'مدير مشروع', 'استشاري مستقل', 'مقاول', 'مستشار تطوير عقاري', 'صانع محتوى', 'أخرى', 'جهة العمل', 'جهة العمل (اختياري)', 'اسم جهة العمل أطول من اللازم', 'شهادة الآيبان', 'PDF أو صورة', 'أرفق شهادة الآيبان', 'الملف أكبر من 10 ميجابايت — اختر ملفاً أصغر', 'ارفع ملف PDF أو صورة PNG أو JPG', 'اسم صاحب الحساب البنكي', 'اسم صاحب الحساب البنكي *', 'اكتب اسم صاحب الحساب كما في شهادة الآيبان', 'السجل التجاري', 'اختياري · PDF أو صورة', 'أرفق السجل التجاري', 'الملف أكبر من 10 ميجابايت — اختر ملفاً أصغر', 'ارفع ملف PDF أو صورة PNG أو JPG', 'شهادة التسجيل الضريبي', 'اختياري · PDF أو صورة', 'أرفق شهادة التسجيل الضريبي', 'الملف أكبر من 10 ميجابايت — اختر ملفاً أصغر', 'ارفع ملف PDF أو صورة PNG أو JPG', 'الموافقة على الشروط والأحكام', 'يلزم الموافقة على الشروط والأحكام وسياسة الخصوصية', 'إقرار عدم التعارض', 'يلزم الإقرار بعدم التعارض', 'وصلنا تسجيلك — سنراجع بياناتك ومستنداتك ونتواصل معك لإصدار كودك.', 'تعذّر استلام تسجيلك الآن. حاول مرة أخرى بعد قليل، أو راسلنا على واتساب.', 'لم يُحفظ تسجيلك بسبب خطأ من جهتنا. حاول مرة أخرى بعد قليل، أو راسلنا على واتساب.', 'ربائد — وصلنا تسجيلك في برنامج الإحالة', 'مرحباً {الاسم}،

وصلنا تسجيلك في برنامج الإحالة. سيراجع فريقنا بياناتك ومستنداتك، ونتواصل معك لإصدار كودك.

فريق ربائد', 'published', now(), now());

SELECT setval(pg_get_serial_sequence('"referral_signup_form"', 'id'), (SELECT max("id") FROM "referral_signup_form"));
`;
