import { type MigrateUpArgs, type MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_partnership_application_form_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__partnership_application_form_v_version_status" AS ENUM('draft', 'published');
  ALTER TYPE "public"."enum_form_submissions_form" ADD VALUE 'partnership-application';
  CREATE TABLE "partnership_application_form" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"alert_address" varchar,
  	"heading" varchar,
  	"lead" varchar,
  	"submit" varchar,
  	"fine_print" varchar,
  	"fields_company_label" varchar,
  	"fields_company_placeholder" varchar,
  	"fields_company_message" varchar,
  	"fields_commercial_registration_label" varchar,
  	"fields_commercial_registration_placeholder" varchar,
  	"fields_commercial_registration_message" varchar,
  	"fields_commercial_registration_too_large" varchar,
  	"fields_commercial_registration_wrong_type" varchar,
  	"fields_city_label" varchar,
  	"fields_city_placeholder" varchar,
  	"fields_city_message" varchar,
  	"fields_name_label" varchar,
  	"fields_name_placeholder" varchar,
  	"fields_name_message" varchar,
  	"fields_job_title_label" varchar,
  	"fields_job_title_placeholder" varchar,
  	"fields_job_title_message" varchar,
  	"fields_phone_label" varchar,
  	"fields_phone_placeholder" varchar,
  	"fields_phone_message" varchar,
  	"fields_email_label" varchar,
  	"fields_email_placeholder" varchar,
  	"fields_email_message" varchar,
  	"fields_activity_label" varchar,
  	"fields_activity_placeholder" varchar,
  	"fields_activity_message" varchar,
  	"fields_activity_options_option_consulting_office" varchar,
  	"fields_activity_options_option_project_management" varchar,
  	"fields_activity_options_option_contracting" varchar,
  	"fields_activity_options_option_real_estate_development" varchar,
  	"fields_activity_options_option_other" varchar,
  	"fields_active_projects_label" varchar,
  	"fields_active_projects_placeholder" varchar,
  	"fields_active_projects_message" varchar,
  	"fields_active_projects_options_option_1_3" varchar,
  	"fields_active_projects_options_option_4_10" varchar,
  	"fields_active_projects_options_option_11_25" varchar,
  	"fields_active_projects_options_option_over_25" varchar,
  	"fields_client_type_label" varchar,
  	"fields_client_type_placeholder" varchar,
  	"fields_client_type_message" varchar,
  	"fields_client_type_options_option_individual_developers" varchar,
  	"fields_client_type_options_option_development_companies" varchar,
  	"fields_client_type_options_option_government" varchar,
  	"fields_client_type_options_option_mixed" varchar,
  	"fields_project_area_label" varchar,
  	"fields_project_area_placeholder" varchar,
  	"fields_project_area_message" varchar,
  	"fields_project_area_options_option_under_5000" varchar,
  	"fields_project_area_options_option_5000_20000" varchar,
  	"fields_project_area_options_option_20000_50000" varchar,
  	"fields_project_area_options_option_over_50000" varchar,
  	"fields_partnership_mode_label" varchar,
  	"fields_partnership_mode_placeholder" varchar,
  	"fields_partnership_mode_message" varchar,
  	"fields_partnership_mode_options_o_embedded_in_proposal" varchar,
  	"fields_partnership_mode_options_o_office_licence" varchar,
  	"fields_partnership_mode_options_o_approved_referral" varchar,
  	"fields_partnership_mode_options_o_undecided" varchar,
  	"fields_goals_label" varchar,
  	"fields_goals_placeholder" varchar,
  	"fields_goals_message" varchar,
  	"received" varchar,
  	"refused" varchar,
  	"failed" varchar,
  	"confirmation_subject" varchar,
  	"confirmation_body" varchar,
  	"_status" "enum_partnership_application_form_status" DEFAULT 'draft',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "_partnership_application_form_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"version_alert_address" varchar,
  	"version_heading" varchar,
  	"version_lead" varchar,
  	"version_submit" varchar,
  	"version_fine_print" varchar,
  	"version_fields_company_label" varchar,
  	"version_fields_company_placeholder" varchar,
  	"version_fields_company_message" varchar,
  	"version_fields_commercial_registration_label" varchar,
  	"version_fields_commercial_registration_placeholder" varchar,
  	"version_fields_commercial_registration_message" varchar,
  	"version_fields_commercial_registration_too_large" varchar,
  	"version_fields_commercial_registration_wrong_type" varchar,
  	"version_fields_city_label" varchar,
  	"version_fields_city_placeholder" varchar,
  	"version_fields_city_message" varchar,
  	"version_fields_name_label" varchar,
  	"version_fields_name_placeholder" varchar,
  	"version_fields_name_message" varchar,
  	"version_fields_job_title_label" varchar,
  	"version_fields_job_title_placeholder" varchar,
  	"version_fields_job_title_message" varchar,
  	"version_fields_phone_label" varchar,
  	"version_fields_phone_placeholder" varchar,
  	"version_fields_phone_message" varchar,
  	"version_fields_email_label" varchar,
  	"version_fields_email_placeholder" varchar,
  	"version_fields_email_message" varchar,
  	"version_fields_activity_label" varchar,
  	"version_fields_activity_placeholder" varchar,
  	"version_fields_activity_message" varchar,
  	"version_fields_activity_options_option_consulting_office" varchar,
  	"version_fields_activity_options_option_project_management" varchar,
  	"version_fields_activity_options_option_contracting" varchar,
  	"version_fields_activity_options_option_real_estate_development" varchar,
  	"version_fields_activity_options_option_other" varchar,
  	"version_fields_active_projects_label" varchar,
  	"version_fields_active_projects_placeholder" varchar,
  	"version_fields_active_projects_message" varchar,
  	"version_fields_active_projects_options_option_1_3" varchar,
  	"version_fields_active_projects_options_option_4_10" varchar,
  	"version_fields_active_projects_options_option_11_25" varchar,
  	"version_fields_active_projects_options_option_over_25" varchar,
  	"version_fields_client_type_label" varchar,
  	"version_fields_client_type_placeholder" varchar,
  	"version_fields_client_type_message" varchar,
  	"version_fields_client_type_options_option_individual_developers" varchar,
  	"version_fields_client_type_options_option_development_companies" varchar,
  	"version_fields_client_type_options_option_government" varchar,
  	"version_fields_client_type_options_option_mixed" varchar,
  	"version_fields_project_area_label" varchar,
  	"version_fields_project_area_placeholder" varchar,
  	"version_fields_project_area_message" varchar,
  	"version_fields_project_area_options_option_under_5000" varchar,
  	"version_fields_project_area_options_option_5000_20000" varchar,
  	"version_fields_project_area_options_option_20000_50000" varchar,
  	"version_fields_project_area_options_option_over_50000" varchar,
  	"version_fields_partnership_mode_label" varchar,
  	"version_fields_partnership_mode_placeholder" varchar,
  	"version_fields_partnership_mode_message" varchar,
  	"version_fields_partnership_mode_options_o_embedded_in_proposal" varchar,
  	"version_fields_partnership_mode_options_o_office_licence" varchar,
  	"version_fields_partnership_mode_options_o_approved_referral" varchar,
  	"version_fields_partnership_mode_options_o_undecided" varchar,
  	"version_fields_goals_label" varchar,
  	"version_fields_goals_placeholder" varchar,
  	"version_fields_goals_message" varchar,
  	"version_received" varchar,
  	"version_refused" varchar,
  	"version_failed" varchar,
  	"version_confirmation_subject" varchar,
  	"version_confirmation_body" varchar,
  	"version__status" "enum__partnership_application_form_v_version_status" DEFAULT 'draft',
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE INDEX "partnership_application_form__status_idx" ON "partnership_application_form" USING btree ("_status");
  CREATE INDEX "_partnership_application_form_v_version_version__status_idx" ON "_partnership_application_form_v" USING btree ("version__status");
  CREATE INDEX "_partnership_application_form_v_created_at_idx" ON "_partnership_application_form_v" USING btree ("created_at");
  CREATE INDEX "_partnership_application_form_v_updated_at_idx" ON "_partnership_application_form_v" USING btree ("updated_at");
  CREATE INDEX "_partnership_application_form_v_latest_idx" ON "_partnership_application_form_v" USING btree ("latest");`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "partnership_application_form" CASCADE;
  DROP TABLE "_partnership_application_form_v" CASCADE;
  ALTER TABLE "form_submissions" ALTER COLUMN "form" SET DATA TYPE text;
  DROP TYPE "public"."enum_form_submissions_form";
  CREATE TYPE "public"."enum_form_submissions_form" AS ENUM('demo-request', 'referral-signup', 'tool-download');
  ALTER TABLE "form_submissions" ALTER COLUMN "form" SET DATA TYPE "public"."enum_form_submissions_form" USING "form"::"public"."enum_form_submissions_form";
  DROP TYPE "public"."enum_partnership_application_form_status";
  DROP TYPE "public"."enum__partnership_application_form_v_version_status";`)
}
