import { sql, type MigrateDownArgs, type MigrateUpArgs } from '@payloadcms/db-postgres';

/**
 * Gives each form an English entry of its own, and each submission the
 * language it was filled in (ticket 42).
 *
 * The four English entries are the Arabic ones' twins, less the alert address,
 * which is one for both languages: `src/cms/globals/form-settings.ts` says why
 * English is an entry of its own rather than a group inside the Arabic one.
 * They are created empty. Until the founder publishes English in them, an
 * English page shows the English its form was written with
 * (`src/forms/definition.ts`), never the Arabic; the English itself is
 * proposed to him as a draft by the next migration.
 *
 * Every submission stored before this was filled in Arabic, which is what the
 * new column says of each.
 */

export async function up({ db }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_form_submissions_locale" AS ENUM('ar', 'en');
  CREATE TYPE "public"."enum_demo_request_form_en_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__demo_request_form_en_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum_referral_signup_form_en_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__referral_signup_form_en_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum_tool_download_form_en_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__tool_download_form_en_v_version_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum_partnership_application_form_en_status" AS ENUM('draft', 'published');
  CREATE TYPE "public"."enum__partnership_application_form_en_v_version_status" AS ENUM('draft', 'published');
  CREATE TABLE "demo_request_form_en" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"heading" varchar,
  	"lead" varchar,
  	"submit" varchar,
  	"fine_print" varchar,
  	"fields_name_label" varchar,
  	"fields_name_placeholder" varchar,
  	"fields_name_message" varchar,
  	"fields_email_label" varchar,
  	"fields_email_placeholder" varchar,
  	"fields_email_message" varchar,
  	"fields_role_label" varchar,
  	"fields_role_placeholder" varchar,
  	"fields_role_message" varchar,
  	"fields_role_options_option_owner" varchar,
  	"fields_role_options_option_consultant" varchar,
  	"fields_role_options_option_contractor" varchar,
  	"fields_phone_label" varchar,
  	"fields_phone_placeholder" varchar,
  	"fields_phone_message" varchar,
  	"fields_company_label" varchar,
  	"fields_company_placeholder" varchar,
  	"fields_company_message" varchar,
  	"fields_active_projects_label" varchar,
  	"fields_active_projects_placeholder" varchar,
  	"fields_active_projects_message" varchar,
  	"received" varchar,
  	"refused" varchar,
  	"failed" varchar,
  	"confirmation_subject" varchar,
  	"confirmation_body" varchar,
  	"_status" "enum_demo_request_form_en_status" DEFAULT 'draft',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "_demo_request_form_en_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"version_heading" varchar,
  	"version_lead" varchar,
  	"version_submit" varchar,
  	"version_fine_print" varchar,
  	"version_fields_name_label" varchar,
  	"version_fields_name_placeholder" varchar,
  	"version_fields_name_message" varchar,
  	"version_fields_email_label" varchar,
  	"version_fields_email_placeholder" varchar,
  	"version_fields_email_message" varchar,
  	"version_fields_role_label" varchar,
  	"version_fields_role_placeholder" varchar,
  	"version_fields_role_message" varchar,
  	"version_fields_role_options_option_owner" varchar,
  	"version_fields_role_options_option_consultant" varchar,
  	"version_fields_role_options_option_contractor" varchar,
  	"version_fields_phone_label" varchar,
  	"version_fields_phone_placeholder" varchar,
  	"version_fields_phone_message" varchar,
  	"version_fields_company_label" varchar,
  	"version_fields_company_placeholder" varchar,
  	"version_fields_company_message" varchar,
  	"version_fields_active_projects_label" varchar,
  	"version_fields_active_projects_placeholder" varchar,
  	"version_fields_active_projects_message" varchar,
  	"version_received" varchar,
  	"version_refused" varchar,
  	"version_failed" varchar,
  	"version_confirmation_subject" varchar,
  	"version_confirmation_body" varchar,
  	"version__status" "enum__demo_request_form_en_v_version_status" DEFAULT 'draft',
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE TABLE "referral_signup_form_en" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"heading" varchar,
  	"lead" varchar,
  	"submit" varchar,
  	"fine_print" varchar,
  	"fields_name_label" varchar,
  	"fields_name_placeholder" varchar,
  	"fields_name_message" varchar,
  	"fields_phone_label" varchar,
  	"fields_phone_placeholder" varchar,
  	"fields_phone_message" varchar,
  	"fields_email_label" varchar,
  	"fields_email_placeholder" varchar,
  	"fields_email_message" varchar,
  	"fields_city_label" varchar,
  	"fields_city_placeholder" varchar,
  	"fields_city_message" varchar,
  	"fields_profession_label" varchar,
  	"fields_profession_placeholder" varchar,
  	"fields_profession_message" varchar,
  	"fields_profession_options_option_engineer" varchar,
  	"fields_profession_options_option_project_manager" varchar,
  	"fields_profession_options_option_independent_consultant" varchar,
  	"fields_profession_options_option_contractor" varchar,
  	"fields_profession_options_option_real_estate_advisor" varchar,
  	"fields_profession_options_option_content_creator" varchar,
  	"fields_profession_options_option_other" varchar,
  	"fields_employer_label" varchar,
  	"fields_employer_placeholder" varchar,
  	"fields_employer_message" varchar,
  	"fields_iban_certificate_label" varchar,
  	"fields_iban_certificate_placeholder" varchar,
  	"fields_iban_certificate_message" varchar,
  	"fields_iban_certificate_too_large" varchar,
  	"fields_iban_certificate_wrong_type" varchar,
  	"fields_account_holder_label" varchar,
  	"fields_account_holder_placeholder" varchar,
  	"fields_account_holder_message" varchar,
  	"fields_commercial_registration_label" varchar,
  	"fields_commercial_registration_placeholder" varchar,
  	"fields_commercial_registration_message" varchar,
  	"fields_commercial_registration_too_large" varchar,
  	"fields_commercial_registration_wrong_type" varchar,
  	"fields_tax_registration_certificate_label" varchar,
  	"fields_tax_registration_certificate_placeholder" varchar,
  	"fields_tax_registration_certificate_message" varchar,
  	"fields_tax_registration_certificate_too_large" varchar,
  	"fields_tax_registration_certificate_wrong_type" varchar,
  	"fields_accept_terms_label" varchar,
  	"fields_accept_terms_message" varchar,
  	"fields_declare_no_conflict_label" varchar,
  	"fields_declare_no_conflict_message" varchar,
  	"received" varchar,
  	"refused" varchar,
  	"failed" varchar,
  	"confirmation_subject" varchar,
  	"confirmation_body" varchar,
  	"_status" "enum_referral_signup_form_en_status" DEFAULT 'draft',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "_referral_signup_form_en_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"version_heading" varchar,
  	"version_lead" varchar,
  	"version_submit" varchar,
  	"version_fine_print" varchar,
  	"version_fields_name_label" varchar,
  	"version_fields_name_placeholder" varchar,
  	"version_fields_name_message" varchar,
  	"version_fields_phone_label" varchar,
  	"version_fields_phone_placeholder" varchar,
  	"version_fields_phone_message" varchar,
  	"version_fields_email_label" varchar,
  	"version_fields_email_placeholder" varchar,
  	"version_fields_email_message" varchar,
  	"version_fields_city_label" varchar,
  	"version_fields_city_placeholder" varchar,
  	"version_fields_city_message" varchar,
  	"version_fields_profession_label" varchar,
  	"version_fields_profession_placeholder" varchar,
  	"version_fields_profession_message" varchar,
  	"version_fields_profession_options_option_engineer" varchar,
  	"version_fields_profession_options_option_project_manager" varchar,
  	"version_fields_profession_options_option_independent_consultant" varchar,
  	"version_fields_profession_options_option_contractor" varchar,
  	"version_fields_profession_options_option_real_estate_advisor" varchar,
  	"version_fields_profession_options_option_content_creator" varchar,
  	"version_fields_profession_options_option_other" varchar,
  	"version_fields_employer_label" varchar,
  	"version_fields_employer_placeholder" varchar,
  	"version_fields_employer_message" varchar,
  	"version_fields_iban_certificate_label" varchar,
  	"version_fields_iban_certificate_placeholder" varchar,
  	"version_fields_iban_certificate_message" varchar,
  	"version_fields_iban_certificate_too_large" varchar,
  	"version_fields_iban_certificate_wrong_type" varchar,
  	"version_fields_account_holder_label" varchar,
  	"version_fields_account_holder_placeholder" varchar,
  	"version_fields_account_holder_message" varchar,
  	"version_fields_commercial_registration_label" varchar,
  	"version_fields_commercial_registration_placeholder" varchar,
  	"version_fields_commercial_registration_message" varchar,
  	"version_fields_commercial_registration_too_large" varchar,
  	"version_fields_commercial_registration_wrong_type" varchar,
  	"version_fields_tax_registration_certificate_label" varchar,
  	"version_fields_tax_registration_certificate_placeholder" varchar,
  	"version_fields_tax_registration_certificate_message" varchar,
  	"version_fields_tax_registration_certificate_too_large" varchar,
  	"version_fields_tax_registration_certificate_wrong_type" varchar,
  	"version_fields_accept_terms_label" varchar,
  	"version_fields_accept_terms_message" varchar,
  	"version_fields_declare_no_conflict_label" varchar,
  	"version_fields_declare_no_conflict_message" varchar,
  	"version_received" varchar,
  	"version_refused" varchar,
  	"version_failed" varchar,
  	"version_confirmation_subject" varchar,
  	"version_confirmation_body" varchar,
  	"version__status" "enum__referral_signup_form_en_v_version_status" DEFAULT 'draft',
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE TABLE "tool_download_form_en" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"heading" varchar,
  	"lead" varchar,
  	"submit" varchar,
  	"fine_print" varchar,
  	"fields_first_name_label" varchar,
  	"fields_first_name_placeholder" varchar,
  	"fields_first_name_message" varchar,
  	"fields_last_name_label" varchar,
  	"fields_last_name_placeholder" varchar,
  	"fields_last_name_message" varchar,
  	"fields_country_code_label" varchar,
  	"fields_country_code_placeholder" varchar,
  	"fields_country_code_message" varchar,
  	"fields_country_code_options_option_966" varchar,
  	"fields_country_code_options_option_971" varchar,
  	"fields_country_code_options_option_965" varchar,
  	"fields_country_code_options_option_974" varchar,
  	"fields_country_code_options_option_973" varchar,
  	"fields_country_code_options_option_968" varchar,
  	"fields_country_code_options_option_962" varchar,
  	"fields_country_code_options_option_20" varchar,
  	"fields_country_code_options_option_90" varchar,
  	"fields_country_code_options_option_other" varchar,
  	"fields_phone_label" varchar,
  	"fields_phone_placeholder" varchar,
  	"fields_phone_message" varchar,
  	"fields_email_label" varchar,
  	"fields_email_placeholder" varchar,
  	"fields_email_message" varchar,
  	"fields_company_label" varchar,
  	"fields_company_placeholder" varchar,
  	"fields_company_message" varchar,
  	"received" varchar,
  	"refused" varchar,
  	"failed" varchar,
  	"confirmation_subject" varchar,
  	"confirmation_body" varchar,
  	"_status" "enum_tool_download_form_en_status" DEFAULT 'draft',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "_tool_download_form_en_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"version_heading" varchar,
  	"version_lead" varchar,
  	"version_submit" varchar,
  	"version_fine_print" varchar,
  	"version_fields_first_name_label" varchar,
  	"version_fields_first_name_placeholder" varchar,
  	"version_fields_first_name_message" varchar,
  	"version_fields_last_name_label" varchar,
  	"version_fields_last_name_placeholder" varchar,
  	"version_fields_last_name_message" varchar,
  	"version_fields_country_code_label" varchar,
  	"version_fields_country_code_placeholder" varchar,
  	"version_fields_country_code_message" varchar,
  	"version_fields_country_code_options_option_966" varchar,
  	"version_fields_country_code_options_option_971" varchar,
  	"version_fields_country_code_options_option_965" varchar,
  	"version_fields_country_code_options_option_974" varchar,
  	"version_fields_country_code_options_option_973" varchar,
  	"version_fields_country_code_options_option_968" varchar,
  	"version_fields_country_code_options_option_962" varchar,
  	"version_fields_country_code_options_option_20" varchar,
  	"version_fields_country_code_options_option_90" varchar,
  	"version_fields_country_code_options_option_other" varchar,
  	"version_fields_phone_label" varchar,
  	"version_fields_phone_placeholder" varchar,
  	"version_fields_phone_message" varchar,
  	"version_fields_email_label" varchar,
  	"version_fields_email_placeholder" varchar,
  	"version_fields_email_message" varchar,
  	"version_fields_company_label" varchar,
  	"version_fields_company_placeholder" varchar,
  	"version_fields_company_message" varchar,
  	"version_received" varchar,
  	"version_refused" varchar,
  	"version_failed" varchar,
  	"version_confirmation_subject" varchar,
  	"version_confirmation_body" varchar,
  	"version__status" "enum__tool_download_form_en_v_version_status" DEFAULT 'draft',
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  CREATE TABLE "partnership_application_form_en" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"heading" varchar,
  	"lead" varchar,
  	"submit" varchar,
  	"fine_print" varchar,
  	"fields_company_label" varchar,
  	"fields_company_placeholder" varchar,
  	"fields_company_message" varchar,
  	"fields_commercial_registration_label" varchar,
  	"fields_commercial_registration_placeholder" varchar,
  	"fields_commercial_registration_message" varchar,
  	"fields_commercial_registration_too_large" varchar,
  	"fields_commercial_registration_wrong_type" varchar,
  	"fields_city_label" varchar,
  	"fields_city_placeholder" varchar,
  	"fields_city_message" varchar,
  	"fields_name_label" varchar,
  	"fields_name_placeholder" varchar,
  	"fields_name_message" varchar,
  	"fields_job_title_label" varchar,
  	"fields_job_title_placeholder" varchar,
  	"fields_job_title_message" varchar,
  	"fields_phone_label" varchar,
  	"fields_phone_placeholder" varchar,
  	"fields_phone_message" varchar,
  	"fields_email_label" varchar,
  	"fields_email_placeholder" varchar,
  	"fields_email_message" varchar,
  	"fields_activity_label" varchar,
  	"fields_activity_placeholder" varchar,
  	"fields_activity_message" varchar,
  	"fields_activity_options_option_consulting_office" varchar,
  	"fields_activity_options_option_project_management" varchar,
  	"fields_activity_options_option_contracting" varchar,
  	"fields_activity_options_option_real_estate_development" varchar,
  	"fields_activity_options_option_other" varchar,
  	"fields_active_projects_label" varchar,
  	"fields_active_projects_placeholder" varchar,
  	"fields_active_projects_message" varchar,
  	"fields_active_projects_options_option_1_3" varchar,
  	"fields_active_projects_options_option_4_10" varchar,
  	"fields_active_projects_options_option_11_25" varchar,
  	"fields_active_projects_options_option_over_25" varchar,
  	"fields_client_type_label" varchar,
  	"fields_client_type_placeholder" varchar,
  	"fields_client_type_message" varchar,
  	"fields_client_type_options_option_individual_developers" varchar,
  	"fields_client_type_options_option_development_companies" varchar,
  	"fields_client_type_options_option_government" varchar,
  	"fields_client_type_options_option_mixed" varchar,
  	"fields_project_area_label" varchar,
  	"fields_project_area_placeholder" varchar,
  	"fields_project_area_message" varchar,
  	"fields_project_area_options_option_under_5000" varchar,
  	"fields_project_area_options_option_5000_20000" varchar,
  	"fields_project_area_options_option_20000_50000" varchar,
  	"fields_project_area_options_option_over_50000" varchar,
  	"fields_partnership_mode_label" varchar,
  	"fields_partnership_mode_placeholder" varchar,
  	"fields_partnership_mode_message" varchar,
  	"fields_partnership_mode_options_o_embedded_in_proposal" varchar,
  	"fields_partnership_mode_options_o_office_licence" varchar,
  	"fields_partnership_mode_options_o_approved_referral" varchar,
  	"fields_partnership_mode_options_o_undecided" varchar,
  	"fields_goals_label" varchar,
  	"fields_goals_placeholder" varchar,
  	"fields_goals_message" varchar,
  	"received" varchar,
  	"refused" varchar,
  	"failed" varchar,
  	"confirmation_subject" varchar,
  	"confirmation_body" varchar,
  	"_status" "enum_partnership_application_form_en_status" DEFAULT 'draft',
  	"updated_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone
  );
  
  CREATE TABLE "_partnership_application_form_en_v" (
  	"id" serial PRIMARY KEY NOT NULL,
  	"version_heading" varchar,
  	"version_lead" varchar,
  	"version_submit" varchar,
  	"version_fine_print" varchar,
  	"version_fields_company_label" varchar,
  	"version_fields_company_placeholder" varchar,
  	"version_fields_company_message" varchar,
  	"version_fields_commercial_registration_label" varchar,
  	"version_fields_commercial_registration_placeholder" varchar,
  	"version_fields_commercial_registration_message" varchar,
  	"version_fields_commercial_registration_too_large" varchar,
  	"version_fields_commercial_registration_wrong_type" varchar,
  	"version_fields_city_label" varchar,
  	"version_fields_city_placeholder" varchar,
  	"version_fields_city_message" varchar,
  	"version_fields_name_label" varchar,
  	"version_fields_name_placeholder" varchar,
  	"version_fields_name_message" varchar,
  	"version_fields_job_title_label" varchar,
  	"version_fields_job_title_placeholder" varchar,
  	"version_fields_job_title_message" varchar,
  	"version_fields_phone_label" varchar,
  	"version_fields_phone_placeholder" varchar,
  	"version_fields_phone_message" varchar,
  	"version_fields_email_label" varchar,
  	"version_fields_email_placeholder" varchar,
  	"version_fields_email_message" varchar,
  	"version_fields_activity_label" varchar,
  	"version_fields_activity_placeholder" varchar,
  	"version_fields_activity_message" varchar,
  	"version_fields_activity_options_option_consulting_office" varchar,
  	"version_fields_activity_options_option_project_management" varchar,
  	"version_fields_activity_options_option_contracting" varchar,
  	"version_fields_activity_options_option_real_estate_development" varchar,
  	"version_fields_activity_options_option_other" varchar,
  	"version_fields_active_projects_label" varchar,
  	"version_fields_active_projects_placeholder" varchar,
  	"version_fields_active_projects_message" varchar,
  	"version_fields_active_projects_options_option_1_3" varchar,
  	"version_fields_active_projects_options_option_4_10" varchar,
  	"version_fields_active_projects_options_option_11_25" varchar,
  	"version_fields_active_projects_options_option_over_25" varchar,
  	"version_fields_client_type_label" varchar,
  	"version_fields_client_type_placeholder" varchar,
  	"version_fields_client_type_message" varchar,
  	"version_fields_client_type_options_option_individual_developers" varchar,
  	"version_fields_client_type_options_option_development_companies" varchar,
  	"version_fields_client_type_options_option_government" varchar,
  	"version_fields_client_type_options_option_mixed" varchar,
  	"version_fields_project_area_label" varchar,
  	"version_fields_project_area_placeholder" varchar,
  	"version_fields_project_area_message" varchar,
  	"version_fields_project_area_options_option_under_5000" varchar,
  	"version_fields_project_area_options_option_5000_20000" varchar,
  	"version_fields_project_area_options_option_20000_50000" varchar,
  	"version_fields_project_area_options_option_over_50000" varchar,
  	"version_fields_partnership_mode_label" varchar,
  	"version_fields_partnership_mode_placeholder" varchar,
  	"version_fields_partnership_mode_message" varchar,
  	"version_fields_partnership_mode_options_o_embedded_in_proposal" varchar,
  	"version_fields_partnership_mode_options_o_office_licence" varchar,
  	"version_fields_partnership_mode_options_o_approved_referral" varchar,
  	"version_fields_partnership_mode_options_o_undecided" varchar,
  	"version_fields_goals_label" varchar,
  	"version_fields_goals_placeholder" varchar,
  	"version_fields_goals_message" varchar,
  	"version_received" varchar,
  	"version_refused" varchar,
  	"version_failed" varchar,
  	"version_confirmation_subject" varchar,
  	"version_confirmation_body" varchar,
  	"version__status" "enum__partnership_application_form_en_v_version_status" DEFAULT 'draft',
  	"version_updated_at" timestamp(3) with time zone,
  	"version_created_at" timestamp(3) with time zone,
  	"created_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"updated_at" timestamp(3) with time zone DEFAULT now() NOT NULL,
  	"latest" boolean
  );
  
  ALTER TABLE "form_submissions" ADD COLUMN "locale" "enum_form_submissions_locale" DEFAULT 'ar' NOT NULL;
  CREATE INDEX "demo_request_form_en__status_idx" ON "demo_request_form_en" USING btree ("_status");
  CREATE INDEX "_demo_request_form_en_v_version_version__status_idx" ON "_demo_request_form_en_v" USING btree ("version__status");
  CREATE INDEX "_demo_request_form_en_v_created_at_idx" ON "_demo_request_form_en_v" USING btree ("created_at");
  CREATE INDEX "_demo_request_form_en_v_updated_at_idx" ON "_demo_request_form_en_v" USING btree ("updated_at");
  CREATE INDEX "_demo_request_form_en_v_latest_idx" ON "_demo_request_form_en_v" USING btree ("latest");
  CREATE INDEX "referral_signup_form_en__status_idx" ON "referral_signup_form_en" USING btree ("_status");
  CREATE INDEX "_referral_signup_form_en_v_version_version__status_idx" ON "_referral_signup_form_en_v" USING btree ("version__status");
  CREATE INDEX "_referral_signup_form_en_v_created_at_idx" ON "_referral_signup_form_en_v" USING btree ("created_at");
  CREATE INDEX "_referral_signup_form_en_v_updated_at_idx" ON "_referral_signup_form_en_v" USING btree ("updated_at");
  CREATE INDEX "_referral_signup_form_en_v_latest_idx" ON "_referral_signup_form_en_v" USING btree ("latest");
  CREATE INDEX "tool_download_form_en__status_idx" ON "tool_download_form_en" USING btree ("_status");
  CREATE INDEX "_tool_download_form_en_v_version_version__status_idx" ON "_tool_download_form_en_v" USING btree ("version__status");
  CREATE INDEX "_tool_download_form_en_v_created_at_idx" ON "_tool_download_form_en_v" USING btree ("created_at");
  CREATE INDEX "_tool_download_form_en_v_updated_at_idx" ON "_tool_download_form_en_v" USING btree ("updated_at");
  CREATE INDEX "_tool_download_form_en_v_latest_idx" ON "_tool_download_form_en_v" USING btree ("latest");
  CREATE INDEX "partnership_application_form_en__status_idx" ON "partnership_application_form_en" USING btree ("_status");
  CREATE INDEX "_partnership_application_form_en_v_version_version__stat_idx" ON "_partnership_application_form_en_v" USING btree ("version__status");
  CREATE INDEX "_partnership_application_form_en_v_created_at_idx" ON "_partnership_application_form_en_v" USING btree ("created_at");
  CREATE INDEX "_partnership_application_form_en_v_updated_at_idx" ON "_partnership_application_form_en_v" USING btree ("updated_at");
  CREATE INDEX "_partnership_application_form_en_v_latest_idx" ON "_partnership_application_form_en_v" USING btree ("latest");`)
}

export async function down({ db }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   DROP TABLE "demo_request_form_en" CASCADE;
  DROP TABLE "_demo_request_form_en_v" CASCADE;
  DROP TABLE "referral_signup_form_en" CASCADE;
  DROP TABLE "_referral_signup_form_en_v" CASCADE;
  DROP TABLE "tool_download_form_en" CASCADE;
  DROP TABLE "_tool_download_form_en_v" CASCADE;
  DROP TABLE "partnership_application_form_en" CASCADE;
  DROP TABLE "_partnership_application_form_en_v" CASCADE;
  ALTER TABLE "form_submissions" DROP COLUMN "locale";
  DROP TYPE "public"."enum_form_submissions_locale";
  DROP TYPE "public"."enum_demo_request_form_en_status";
  DROP TYPE "public"."enum__demo_request_form_en_v_version_status";
  DROP TYPE "public"."enum_referral_signup_form_en_status";
  DROP TYPE "public"."enum__referral_signup_form_en_v_version_status";
  DROP TYPE "public"."enum_tool_download_form_en_status";
  DROP TYPE "public"."enum__tool_download_form_en_v_version_status";
  DROP TYPE "public"."enum_partnership_application_form_en_status";
  DROP TYPE "public"."enum__partnership_application_form_en_v_version_status";`)
}
