/**
 * Copies the self-hosted webfonts out of node_modules into `assets/fonts/`
 * and writes the two stylesheets that declare them:
 *
 *   fonts.css       every family, including the Pour Tracker's. The baseline
 *                   capture answers each Reference page's Google Fonts request
 *                   out of this file (ticket 02).
 *   site-fonts.css  only the families the Marketing site itself renders, so
 *                   the Next.js build never carries the Pour Tracker's
 *                   typeface into production CSS (ticket 03).
 *
 * The Reference site pulls IBM Plex Sans Arabic and DM Mono from Google Fonts.
 * We never depend on that at capture or build time: a missing Arabic font
 * silently falls back to a Latin face and invalidates every visual baseline
 * (ticket 02), and the spec requires the rebuild to self-host `woff2` anyway.
 *
 * Run: npm run fonts:sync
 * Output is committed. Re-run only when the @fontsource versions change.
 */
import { mkdir, readFile, writeFile, copyFile, rm } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const outDir = path.join(repoRoot, 'assets', 'fonts');

/**
 * Exactly the families, weights and subsets the Reference site asks Google for.
 * Two different stylesheets are requested across the nine pages plus the tool:
 *
 *   the nine pages:  IBM+Plex+Sans+Arabic:wght@400;500;600;700
 *                    DM+Mono:wght@400;500
 *   pour-tracker:    Plus+Jakarta+Sans:wght@400;500;600;700;800
 *                    IBM+Plex+Sans+Arabic:wght@400;500;600;700
 *
 * Subsets mirror the ones Google serves for each family, so the unicode-range
 * split — and therefore which glyph comes from which file — is identical.
 *
 * Plus Jakarta Sans belongs to the Pour Tracker's own claymorphic design
 * system, which the spec keeps intact rather than unifying. It is here so the
 * tool's baselines are captured in its real typeface; the rebuilt site itself
 * uses only the families marked `site`.
 */
const FAMILIES = [
  {
    pkg: '@fontsource/ibm-plex-sans-arabic',
    filePrefix: 'ibm-plex-sans-arabic',
    weights: [400, 500, 600, 700],
    subsets: ['arabic', 'latin', 'latin-ext', 'cyrillic-ext'],
    site: true,
  },
  {
    pkg: '@fontsource/dm-mono',
    filePrefix: 'dm-mono',
    weights: [400, 500],
    subsets: ['latin', 'latin-ext'],
    site: true,
  },
  {
    pkg: '@fontsource/plus-jakarta-sans',
    filePrefix: 'plus-jakarta-sans',
    weights: [400, 500, 600, 700, 800],
    subsets: ['latin', 'latin-ext', 'vietnamese', 'cyrillic-ext'],
    site: false,
  },
];

const BANNER = '/* Generated by scripts/sync-fonts.mjs — do not edit by hand. */';

async function main() {
  await rm(outDir, { recursive: true, force: true });
  await mkdir(outDir, { recursive: true });

  const css = [BANNER, ''];
  const siteCss = [BANNER, ''];

  for (const family of FAMILIES) {
    // Every family lands in fonts.css; only the site's families also land in
    // site-fonts.css, which is what the Next.js build imports.
    const sheets = family.site ? [css, siteCss] : [css];
    const pkgDir = path.join(repoRoot, 'node_modules', ...family.pkg.split('/'));
    const unicodeRanges = JSON.parse(await readFile(path.join(pkgDir, 'unicode.json'), 'utf8'));
    const { version } = JSON.parse(await readFile(path.join(pkgDir, 'package.json'), 'utf8'));

    for (const sheet of sheets) sheet.push(`/* ${family.pkg}@${version} */`);

    for (const weight of family.weights) {
      for (const subset of family.subsets) {
        const basename = `${family.filePrefix}-${subset}-${weight}-normal`;
        const range = unicodeRanges[subset];
        if (!range) throw new Error(`No unicode-range for subset "${subset}" in ${family.pkg}`);

        await copyFile(
          path.join(pkgDir, 'files', `${basename}.woff2`),
          path.join(outDir, `${basename}.woff2`),
        );

        const declaration = await readFile(path.join(pkgDir, `${subset}-${weight}.css`), 'utf8');
        const fontFamily = declaration.match(/font-family:\s*('[^']+')/)[1];

        const face = [
          '@font-face {',
          `  font-family: ${fontFamily};`,
          '  font-style: normal;',
          '  font-display: swap;',
          `  font-weight: ${weight};`,
          `  src: url(./${basename}.woff2) format('woff2');`,
          `  unicode-range: ${range};`,
          '}',
          '',
        ];
        for (const sheet of sheets) sheet.push(...face);
      }
    }

    await copyFile(path.join(pkgDir, 'LICENSE'), path.join(outDir, `LICENSE-${family.filePrefix}.txt`));
  }

  await writeFile(path.join(outDir, 'fonts.css'), css.join('\n'), 'utf8');
  await writeFile(path.join(outDir, 'site-fonts.css'), siteCss.join('\n'), 'utf8');
  console.log(`Wrote ${outDir}`);
}

await main();
