/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    'case-studies': CaseStudy;
    'legal-documents': LegalDocument;
    'faq-entries': FaqEntry;
    'form-submissions': FormSubmission;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    'case-studies': CaseStudiesSelect<false> | CaseStudiesSelect<true>;
    'legal-documents': LegalDocumentsSelect<false> | LegalDocumentsSelect<true>;
    'faq-entries': FaqEntriesSelect<false> | FaqEntriesSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'demo-request-form': DemoRequestForm;
    'referral-signup-form': ReferralSignupForm;
    'start-page': StartPage;
    'tool-page': ToolPage;
    'product-page': ProductPage;
    'closing-section': ClosingSection;
    'screen-mocks': ScreenMock;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'demo-request-form': DemoRequestFormSelect<false> | DemoRequestFormSelect<true>;
    'referral-signup-form': ReferralSignupFormSelect<false> | ReferralSignupFormSelect<true>;
    'start-page': StartPageSelect<false> | StartPageSelect<true>;
    'tool-page': ToolPageSelect<false> | ToolPageSelect<true>;
    'product-page': ProductPageSelect<false> | ProductPageSelect<true>;
    'closing-section': ClosingSectionSelect<false> | ClosingSectionSelect<true>;
    'screen-mocks': ScreenMocksSelect<false> | ScreenMocksSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  /**
   * The first paragraph under the title: a standalone answer of 30 to 60 words to the question the article is about. It is what search engines and AI assistants quote.
   */
  answer: string;
  coverImage: number | Media;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * A line or two shown under the title on the blog index, and as the description in search results.
   */
  summary: string;
  /**
   * The end of the address: rabaedapp.com/blog/… — a translation uses the same slug.
   */
  slug: string;
  locale: 'ar' | 'en';
  /**
   * The person who wrote it, not the company.
   */
  author: string;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies".
 */
export interface CaseStudy {
  id: number;
  title: string;
  /**
   * The first paragraph under the title: a standalone answer of 30 to 60 words to what the client achieved with Rabaed. It is what search engines and AI assistants quote.
   */
  answer: string;
  /**
   * The client’s name, as they agreed to have it shown.
   */
  client: string;
  /**
   * For example: residential, commercial buildings.
   */
  sector: string;
  coverImage?: (number | null) | Media;
  challenge: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  whatChanged: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  outcome: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Add a figure only if it was actually measured on the client’s project. A case study publishes without any.
   */
  figures?:
    | {
        value: string;
        label: string;
        /**
         * Shown under the figure: on which project, over what period.
         */
        basis: string;
        id?: string | null;
      }[]
    | null;
  /**
   * In the client’s own words, with their permission. Leave it empty if there is none.
   */
  quote?: {
    text?: string | null;
    name?: string | null;
    role?: string | null;
  };
  images?: (number | Media)[] | null;
  /**
   * A line or two shown under the title on the case studies index, and as the description in search results.
   */
  summary: string;
  /**
   * The end of the address: rabaedapp.com/case-studies/… — a translation uses the same slug.
   */
  slug: string;
  locale: 'ar' | 'en';
  /**
   * The person who wrote it, not the company.
   */
  author: string;
  publishedAt: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * The Arabic text is binding. Every save is kept as a version with its date and who saved it, and reaches the site only when published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents".
 */
export interface LegalDocument {
  id: number;
  slug: 'terms' | 'privacy' | 'referral-terms';
  /**
   * Recorded with every version. The full history is under Versions.
   */
  editedBy?: string | null;
  title: string;
  lead: string;
  metaTitle: string;
  description: string;
  intro: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Clauses are numbered by their order.
   */
  clauses: {
    heading: string;
    inContents?: boolean | null;
    body?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Shown framed, after the text. Leave empty for no contact box.
     */
    contact?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    id?: string | null;
  }[];
  seeAlso: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Drag questions in the list to order them. Each page shows its questions in that order, once published.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-entries".
 */
export interface FaqEntry {
  id: number;
  _order?: string | null;
  question: string;
  /**
   * Put a file name or other English text between backticks to set it left to right, like `concrete_db.json`. Write {payout} for the referral payout and {clientDiscount} for the client discount: the site inserts the current value instead of a typed number.
   */
  answer: string;
  page: 'home' | 'start' | 'tool' | 'referral' | 'partnership';
  locale: 'ar' | 'en';
  /**
   * Untick to hide the question, keeping its words and its place.
   */
  shows?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Every request sent from the site’s forms, newest first.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: number;
  form: 'demo-request' | 'referral-signup' | 'tool-download';
  name?: string | null;
  email?: string | null;
  phone?: string | null;
  answers?:
    | {
        label?: string | null;
        value?: string | null;
        option?: string | null;
        field?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Each document opens through a link that lasts 10 minutes, for signed-in editors only. Open the record again if a link has expired.
   */
  documents?:
    | {
        label?: string | null;
        fileName?: string | null;
        link?: string | null;
        contentType?: string | null;
        size?: number | null;
        field?: string | null;
        key?: string | null;
        id?: string | null;
      }[]
    | null;
  alert?: ('sent' | 'skipped' | 'failed') | null;
  confirmation?: ('sent' | 'skipped' | 'failed') | null;
  token?: string | null;
  sourceHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'case-studies';
        value: number | CaseStudy;
      } | null)
    | ({
        relationTo: 'legal-documents';
        value: number | LegalDocument;
      } | null)
    | ({
        relationTo: 'faq-entries';
        value: number | FaqEntry;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: number | FormSubmission;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  answer?: T;
  coverImage?: T;
  body?: T;
  summary?: T;
  slug?: T;
  locale?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "case-studies_select".
 */
export interface CaseStudiesSelect<T extends boolean = true> {
  title?: T;
  answer?: T;
  client?: T;
  sector?: T;
  coverImage?: T;
  challenge?: T;
  whatChanged?: T;
  outcome?: T;
  figures?:
    | T
    | {
        value?: T;
        label?: T;
        basis?: T;
        id?: T;
      };
  quote?:
    | T
    | {
        text?: T;
        name?: T;
        role?: T;
      };
  images?: T;
  summary?: T;
  slug?: T;
  locale?: T;
  author?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "legal-documents_select".
 */
export interface LegalDocumentsSelect<T extends boolean = true> {
  slug?: T;
  editedBy?: T;
  title?: T;
  lead?: T;
  metaTitle?: T;
  description?: T;
  intro?: T;
  clauses?:
    | T
    | {
        heading?: T;
        inContents?: T;
        body?: T;
        contact?: T;
        id?: T;
      };
  seeAlso?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "faq-entries_select".
 */
export interface FaqEntriesSelect<T extends boolean = true> {
  _order?: T;
  question?: T;
  answer?: T;
  page?: T;
  locale?: T;
  shows?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  name?: T;
  email?: T;
  phone?: T;
  answers?:
    | T
    | {
        label?: T;
        value?: T;
        option?: T;
        field?: T;
        id?: T;
      };
  documents?:
    | T
    | {
        label?: T;
        fileName?: T;
        link?: T;
        contentType?: T;
        size?: T;
        field?: T;
        key?: T;
        id?: T;
      };
  alert?: T;
  confirmation?: T;
  token?: T;
  sourceHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  /**
   * International format, digits only — for example 966576767900. Shown in every page footer.
   */
  whatsappNumber: string;
  email?: string | null;
  /**
   * For example +966576767900
   */
  phone?: string | null;
  /**
   * Leave a field empty if the account is not ready yet.
   */
  social?: {
    linkedin?: string | null;
    x?: string | null;
    facebook?: string | null;
    instagram?: string | null;
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demo-request-form".
 */
export interface DemoRequestForm {
  id: number;
  /**
   * Every request sent from this form is alerted here. While it is empty no email is sent at all — no alert, and no confirmation to the applicant — and every request is still kept under Form submissions.
   */
  alertAddress?: string | null;
  heading: string;
  lead: string;
  submit: string;
  finePrint: string;
  fields: {
    name: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
    email: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
    role: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
      options: {
        option_owner: string;
        option_consultant: string;
        option_contractor: string;
      };
    };
    phone: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
    company: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
    activeProjects: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
  };
  received: string;
  /**
   * For a request that looks automated, or too many from one address within an hour.
   */
  refused: string;
  failed: string;
  confirmationSubject: string;
  /**
   * Write {الاسم} where the applicant’s name goes.
   */
  confirmationBody: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-signup-form".
 */
export interface ReferralSignupForm {
  id: number;
  /**
   * Every request sent from this form is alerted here. While it is empty no email is sent at all — no alert, and no confirmation to the applicant — and every request is still kept under Form submissions.
   */
  alertAddress?: string | null;
  heading: string;
  lead: string;
  submit: string;
  finePrint: string;
  fields: {
    name: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
    phone: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
    email: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
    city: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
    profession: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
      options: {
        option_engineer: string;
        option_project_manager: string;
        option_independent_consultant: string;
        option_contractor: string;
        option_real_estate_advisor: string;
        option_content_creator: string;
        option_other: string;
      };
    };
    employer: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
    ibanCertificate: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      message: string;
      tooLarge: string;
      wrongType: string;
    };
    accountHolder: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      /**
       * Shown under the field while its answer is not acceptable.
       */
      message: string;
    };
    commercialRegistration: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      message: string;
      tooLarge: string;
      wrongType: string;
    };
    taxRegistrationCertificate: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      placeholder: string;
      message: string;
      tooLarge: string;
      wrongType: string;
    };
    acceptTerms: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      /**
       * Shown under the box while it is not ticked.
       */
      message: string;
    };
    declareNoConflict: {
      /**
       * Read out by screen readers, and shown in Form submissions.
       */
      label: string;
      /**
       * Shown under the box while it is not ticked.
       */
      message: string;
    };
  };
  received: string;
  /**
   * For a request that looks automated, or too many from one address within an hour.
   */
  refused: string;
  failed: string;
  confirmationSubject: string;
  /**
   * Write {الاسم} where the applicant’s name goes.
   */
  confirmationBody: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "start-page".
 */
export interface StartPage {
  id: number;
  /**
   * Arabic always. Add English once every word of the page is written in English.
   */
  languages: ('ar' | 'en')[];
  hero: {
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    title: {
      ar: string;
      en?: string | null;
    };
    lead: {
      ar: string;
      en?: string | null;
    };
    /**
     * Leads to the demo request form.
     */
    primaryLabel: {
      ar: string;
      en?: string | null;
    };
    /**
     * Leads to the questions.
     */
    secondaryLabel: {
      ar: string;
      en?: string | null;
    };
  };
  trustStrip?: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
  };
  steps: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    /**
     * Steps are numbered by their order. Drag them to reorder.
     */
    steps: {
      label: {
        ar: string;
        en?: string | null;
      };
      title: {
        ar: string;
        en?: string | null;
      };
      text: {
        ar: string;
        en?: string | null;
      };
      /**
       * The step the section wants remembered, like the guarantee.
       */
      markedOut?: boolean | null;
      id?: string | null;
    }[];
  };
  questions: {
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
  };
  freeTool: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    text: {
      ar: string;
      en?: string | null;
    };
    /**
     * Leads to the tool page.
     */
    linkLabel: {
      ar: string;
      en?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-page".
 */
export interface ToolPage {
  id: number;
  /**
   * Arabic always. Add English once every word of the page is written in English.
   */
  languages: ('ar' | 'en')[];
  hero: {
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    title: {
      ar: string;
      en?: string | null;
    };
    /**
     * Shown in the accent colour after the heading.
     */
    titleAccent: {
      ar: string;
      en?: string | null;
    };
    lead: {
      ar: string;
      en?: string | null;
    };
    /**
     * Leads to the download section.
     */
    primaryLabel: {
      ar: string;
      en?: string | null;
    };
    /**
     * Leads to How it works.
     */
    secondaryLabel: {
      ar: string;
      en?: string | null;
    };
    promises: {
      text: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
    /**
     * The drawing of the tool’s screen beside the heading. Its rows are fixed: three counts, and two pours of two tests each.
     */
    mock: {
      project: {
        ar: string;
        en?: string | null;
      };
      tiles: {
        figure: string;
        tone: 'plain' | 'warn' | 'bad';
        label: {
          ar: string;
          en?: string | null;
        };
        id?: string | null;
      }[];
      pours: {
        reference: string;
        name: {
          ar: string;
          en?: string | null;
        };
        tests: {
          label: {
            ar: string;
            en?: string | null;
          };
          tone: 'idle' | 'warn' | 'bad' | 'info' | 'ok';
          state: {
            ar: string;
            en?: string | null;
          };
          id?: string | null;
        }[];
        id?: string | null;
      }[];
    };
  };
  why: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    lead: {
      ar: string;
      en?: string | null;
    };
    /**
     * Cards are numbered by their order. Drag them to reorder.
     */
    cards: {
      title: {
        ar: string;
        en?: string | null;
      };
      text: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
  };
  features: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    lead: {
      ar: string;
      en?: string | null;
    };
    /**
     * It carries the legend of a test’s state colours under its text.
     */
    countdown: {
      title: {
        ar: string;
        en?: string | null;
      };
      text: {
        ar: string;
        en?: string | null;
      };
      legend: {
        idle: {
          ar: string;
          en?: string | null;
        };
        warn: {
          ar: string;
          en?: string | null;
        };
        bad: {
          ar: string;
          en?: string | null;
        };
        info: {
          ar: string;
          en?: string | null;
        };
        ok: {
          ar: string;
          en?: string | null;
        };
      };
    };
    /**
     * Cards are numbered by their order. Drag them to reorder.
     */
    cards: {
      title: {
        ar: string;
        en?: string | null;
      };
      text: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
    also: {
      text: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
  };
  how: {
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    lead: {
      ar: string;
      en?: string | null;
    };
    /**
     * Steps are numbered by their order. Drag them to reorder.
     */
    steps: {
      label: {
        ar: string;
        en?: string | null;
      };
      title: {
        ar: string;
        en?: string | null;
      };
      text: {
        ar: string;
        en?: string | null;
      };
      /**
       * The step the section wants remembered, like choosing the folder.
       */
      markedOut?: boolean | null;
      id?: string | null;
    }[];
  };
  privacy: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    points: {
      bold: {
        ar: string;
        en?: string | null;
      };
      /**
       * Put a Latin file name between two ` marks to set it left to right, like `concrete_db.json`.
       */
      text: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
    /**
     * The folder the tool writes, drawn as a tree.
     */
    tree: {
      project: {
        ar: string;
        en?: string | null;
      };
      entries: {
        name: string;
        description?: {
          ar?: string | null;
          en?: string | null;
        };
        nested?: boolean | null;
        id?: string | null;
      }[];
      caption: {
        ar: string;
        en?: string | null;
      };
    };
  };
  requirements: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    cards: {
      label: {
        ar: string;
        en?: string | null;
      };
      title: {
        ar: string;
        en?: string | null;
      };
      text: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
  };
  download: {
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    lead: {
      ar: string;
      en?: string | null;
    };
    ticks: {
      text: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
    promise: {
      bold: {
        ar: string;
        en?: string | null;
      };
      text: {
        ar: string;
        en?: string | null;
      };
    };
  };
  questions: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
  };
  upsell: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    lead: {
      ar: string;
      en?: string | null;
    };
    /**
     * Leads to the start page.
     */
    primaryLabel: {
      ar: string;
      en?: string | null;
    };
    /**
     * Leads to the product page.
     */
    secondaryLabel: {
      ar: string;
      en?: string | null;
    };
    adds: {
      text: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
    signOff: {
      ar: string;
      en?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-page".
 */
export interface ProductPage {
  id: number;
  /**
   * Arabic always. Add English once every word of the page is written in English.
   */
  languages: ('ar' | 'en')[];
  hero: {
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    title: {
      ar: string;
      en?: string | null;
    };
    lead: {
      ar: string;
      en?: string | null;
    };
    /**
     * Leads to the demo request form.
     */
    primaryLabel: {
      ar: string;
      en?: string | null;
    };
    /**
     * Leads to the units.
     */
    secondaryLabel: {
      ar: string;
      en?: string | null;
    };
  };
  trustStrip?: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
  };
  journey: {
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    /**
     * On one line: the panels start under it.
     */
    heading: {
      ar: string;
      en?: string | null;
    };
    /**
     * Shows in place of the number on the marked-out panel, like «المخرَج».
     */
    outputLabel: {
      ar: string;
      en?: string | null;
    };
    /**
     * Units are numbered by their order. Drag them to reorder.
     */
    panels: {
      /**
       * A marked-out panel carrying the name above instead of a number, like the Record.
       */
      final?: boolean | null;
      title: {
        ar: string;
        en?: string | null;
      };
      tagline: {
        ar: string;
        en?: string | null;
      };
      body: {
        ar: string;
        en?: string | null;
      };
      /**
       * Who the unit passes things between, right to left. Leave it empty to show none.
       */
      flow?:
        | {
            party: {
              ar: string;
              en?: string | null;
            };
            /**
             * Nothing is drawn after the last party.
             */
            after: 'towards' | 'then' | 'none';
            id?: string | null;
          }[]
        | null;
      /**
       * Its picture and description are under Screen mocks.
       */
      screen:
        | 'correspondence'
        | 'kanban'
        | 'daily-report'
        | 'documents'
        | 'stamped-sheet'
        | 'overview'
        | 'approvals-table'
        | 'submittal';
      id?: string | null;
    }[];
  };
  customStrip: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    badge: {
      ar: string;
      en?: string | null;
    };
    features: {
      /**
       * Short: the badge sits in the card’s corner, over where it runs.
       */
      title: {
        ar: string;
        en?: string | null;
      };
      body: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
    /**
     * Leads to the demo request form.
     */
    askLabel: {
      ar: string;
      en?: string | null;
    };
  };
  roles: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    /**
     * Always three: the Owner, the Consultant and the Contractor. Drag them to reorder.
     */
    roles: {
      party: {
        ar: string;
        en?: string | null;
      };
      promise: {
        ar: string;
        en?: string | null;
      };
      body: {
        ar: string;
        en?: string | null;
      };
      objection: {
        ar: string;
        en?: string | null;
      };
      answer: {
        ar: string;
        en?: string | null;
      };
      /**
       * Its picture and description are under Screen mocks.
       */
      screen:
        | 'correspondence'
        | 'kanban'
        | 'daily-report'
        | 'documents'
        | 'stamped-sheet'
        | 'overview'
        | 'approvals-table'
        | 'submittal';
      id?: string | null;
    }[];
    sharedPromises: {
      promise: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
  };
  innerCycle: {
    /**
     * Untick to hide this section, keeping its words.
     */
    shows?: boolean | null;
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    lead: {
      ar: string;
      en?: string | null;
    };
    /**
     * Always three, in the order a transaction travels: from the Contractor, to the Consultant, to the Owner.
     */
    cycles: {
      party: {
        ar: string;
        en?: string | null;
      };
      note: {
        ar: string;
        en?: string | null;
      };
      /**
       * The last one decides.
       */
      reviewers: {
        reviewer: {
          ar: string;
          en?: string | null;
        };
        id?: string | null;
      }[];
      crosses: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
    privateTag: {
      ar: string;
      en?: string | null;
    };
    crossesLabel: {
      ar: string;
      en?: string | null;
    };
    reviewAgain: {
      ar: string;
      en?: string | null;
    };
    staysInside: {
      label: {
        ar: string;
        en?: string | null;
      };
      text: {
        ar: string;
        en?: string | null;
      };
      emphasis: {
        ar: string;
        en?: string | null;
      };
    };
    crossesOut: {
      label: {
        ar: string;
        en?: string | null;
      };
      text: {
        ar: string;
        en?: string | null;
      };
      emphasis: {
        ar: string;
        en?: string | null;
      };
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "closing-section".
 */
export interface ClosingSection {
  id: number;
  /**
   * Arabic always. Add English once every word of the page is written in English.
   */
  languages: ('ar' | 'en')[];
  closing: {
    eyebrow: {
      ar: string;
      en?: string | null;
    };
    heading: {
      ar: string;
      en?: string | null;
    };
    /**
     * Steps are numbered by their order. Drag them to reorder.
     */
    steps: {
      /**
       * On one line, beside the text.
       */
      label: {
        ar: string;
        en?: string | null;
      };
      text: {
        ar: string;
        en?: string | null;
      };
      id?: string | null;
    }[];
    /**
     * Leads to the start page.
     */
    moreLabel: {
      ar: string;
      en?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "screen-mocks".
 */
export interface ScreenMock {
  id: number;
  /**
   * Arabic always. Add English once every word of the page is written in English.
   */
  languages: ('ar' | 'en')[];
  correspondence: {
    /**
     * 1440×900, or larger in the same proportions. Remove it to bring back the exported image.
     */
    picture?: (number | null) | Media;
    /**
     * Read out by screen readers, and written under the picture. If you replace the picture, describe the new one.
     */
    description: {
      ar: string;
      en?: string | null;
    };
  };
  kanban: {
    /**
     * 1440×900, or larger in the same proportions. Remove it to bring back the exported image.
     */
    picture?: (number | null) | Media;
    /**
     * Read out by screen readers, and written under the picture. If you replace the picture, describe the new one.
     */
    description: {
      ar: string;
      en?: string | null;
    };
  };
  dailyReport: {
    /**
     * 1440×900, or larger in the same proportions. Remove it to bring back the exported image.
     */
    picture?: (number | null) | Media;
    /**
     * Read out by screen readers, and written under the picture. If you replace the picture, describe the new one.
     */
    description: {
      ar: string;
      en?: string | null;
    };
  };
  documents: {
    /**
     * 1440×900, or larger in the same proportions. Remove it to bring back the exported image.
     */
    picture?: (number | null) | Media;
    /**
     * Read out by screen readers, and written under the picture. If you replace the picture, describe the new one.
     */
    description: {
      ar: string;
      en?: string | null;
    };
  };
  stampedSheet: {
    /**
     * 1440×900, or larger in the same proportions. Remove it to bring back the exported image.
     */
    picture?: (number | null) | Media;
    /**
     * Read out by screen readers, and written under the picture. If you replace the picture, describe the new one.
     */
    description: {
      ar: string;
      en?: string | null;
    };
  };
  overview: {
    /**
     * 1440×900, or larger in the same proportions. Remove it to bring back the exported image.
     */
    picture?: (number | null) | Media;
    /**
     * Read out by screen readers, and written under the picture. If you replace the picture, describe the new one.
     */
    description: {
      ar: string;
      en?: string | null;
    };
  };
  approvalsTable: {
    /**
     * 1440×900, or larger in the same proportions. Remove it to bring back the exported image.
     */
    picture?: (number | null) | Media;
    /**
     * Read out by screen readers, and written under the picture. If you replace the picture, describe the new one.
     */
    description: {
      ar: string;
      en?: string | null;
    };
  };
  submittal: {
    /**
     * 1440×900, or larger in the same proportions. Remove it to bring back the exported image.
     */
    picture?: (number | null) | Media;
    /**
     * Read out by screen readers, and written under the picture. If you replace the picture, describe the new one.
     */
    description: {
      ar: string;
      en?: string | null;
    };
  };
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  whatsappNumber?: T;
  email?: T;
  phone?: T;
  social?:
    | T
    | {
        linkedin?: T;
        x?: T;
        facebook?: T;
        instagram?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "demo-request-form_select".
 */
export interface DemoRequestFormSelect<T extends boolean = true> {
  alertAddress?: T;
  heading?: T;
  lead?: T;
  submit?: T;
  finePrint?: T;
  fields?:
    | T
    | {
        name?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
        email?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
        role?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
              options?:
                | T
                | {
                    option_owner?: T;
                    option_consultant?: T;
                    option_contractor?: T;
                  };
            };
        phone?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
        company?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
        activeProjects?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
      };
  received?: T;
  refused?: T;
  failed?: T;
  confirmationSubject?: T;
  confirmationBody?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referral-signup-form_select".
 */
export interface ReferralSignupFormSelect<T extends boolean = true> {
  alertAddress?: T;
  heading?: T;
  lead?: T;
  submit?: T;
  finePrint?: T;
  fields?:
    | T
    | {
        name?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
        phone?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
        email?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
        city?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
        profession?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
              options?:
                | T
                | {
                    option_engineer?: T;
                    option_project_manager?: T;
                    option_independent_consultant?: T;
                    option_contractor?: T;
                    option_real_estate_advisor?: T;
                    option_content_creator?: T;
                    option_other?: T;
                  };
            };
        employer?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
        ibanCertificate?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
              tooLarge?: T;
              wrongType?: T;
            };
        accountHolder?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
            };
        commercialRegistration?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
              tooLarge?: T;
              wrongType?: T;
            };
        taxRegistrationCertificate?:
          | T
          | {
              label?: T;
              placeholder?: T;
              message?: T;
              tooLarge?: T;
              wrongType?: T;
            };
        acceptTerms?:
          | T
          | {
              label?: T;
              message?: T;
            };
        declareNoConflict?:
          | T
          | {
              label?: T;
              message?: T;
            };
      };
  received?: T;
  refused?: T;
  failed?: T;
  confirmationSubject?: T;
  confirmationBody?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "start-page_select".
 */
export interface StartPageSelect<T extends boolean = true> {
  languages?: T;
  hero?:
    | T
    | {
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        primaryLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        secondaryLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  trustStrip?:
    | T
    | {
        shows?: T;
      };
  steps?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        steps?:
          | T
          | {
              label?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              title?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              markedOut?: T;
              id?: T;
            };
      };
  questions?:
    | T
    | {
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  freeTool?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        text?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        linkLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tool-page_select".
 */
export interface ToolPageSelect<T extends boolean = true> {
  languages?: T;
  hero?:
    | T
    | {
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        titleAccent?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        primaryLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        secondaryLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        promises?:
          | T
          | {
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
        mock?:
          | T
          | {
              project?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              tiles?:
                | T
                | {
                    figure?: T;
                    tone?: T;
                    label?:
                      | T
                      | {
                          ar?: T;
                          en?: T;
                        };
                    id?: T;
                  };
              pours?:
                | T
                | {
                    reference?: T;
                    name?:
                      | T
                      | {
                          ar?: T;
                          en?: T;
                        };
                    tests?:
                      | T
                      | {
                          label?:
                            | T
                            | {
                                ar?: T;
                                en?: T;
                              };
                          tone?: T;
                          state?:
                            | T
                            | {
                                ar?: T;
                                en?: T;
                              };
                          id?: T;
                        };
                    id?: T;
                  };
            };
      };
  why?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        cards?:
          | T
          | {
              title?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
      };
  features?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        countdown?:
          | T
          | {
              title?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              legend?:
                | T
                | {
                    idle?:
                      | T
                      | {
                          ar?: T;
                          en?: T;
                        };
                    warn?:
                      | T
                      | {
                          ar?: T;
                          en?: T;
                        };
                    bad?:
                      | T
                      | {
                          ar?: T;
                          en?: T;
                        };
                    info?:
                      | T
                      | {
                          ar?: T;
                          en?: T;
                        };
                    ok?:
                      | T
                      | {
                          ar?: T;
                          en?: T;
                        };
                  };
            };
        cards?:
          | T
          | {
              title?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
        also?:
          | T
          | {
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
      };
  how?:
    | T
    | {
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        steps?:
          | T
          | {
              label?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              title?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              markedOut?: T;
              id?: T;
            };
      };
  privacy?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        points?:
          | T
          | {
              bold?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
        tree?:
          | T
          | {
              project?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              entries?:
                | T
                | {
                    name?: T;
                    description?:
                      | T
                      | {
                          ar?: T;
                          en?: T;
                        };
                    nested?: T;
                    id?: T;
                  };
              caption?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
            };
      };
  requirements?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        cards?:
          | T
          | {
              label?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              title?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
      };
  download?:
    | T
    | {
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        ticks?:
          | T
          | {
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
        promise?:
          | T
          | {
              bold?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
            };
      };
  questions?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  upsell?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        primaryLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        secondaryLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        adds?:
          | T
          | {
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
        signOff?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "product-page_select".
 */
export interface ProductPageSelect<T extends boolean = true> {
  languages?: T;
  hero?:
    | T
    | {
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        title?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        primaryLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        secondaryLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  trustStrip?:
    | T
    | {
        shows?: T;
      };
  journey?:
    | T
    | {
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        outputLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        panels?:
          | T
          | {
              final?: T;
              title?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              tagline?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              body?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              flow?:
                | T
                | {
                    party?:
                      | T
                      | {
                          ar?: T;
                          en?: T;
                        };
                    after?: T;
                    id?: T;
                  };
              screen?: T;
              id?: T;
            };
      };
  customStrip?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        badge?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        features?:
          | T
          | {
              title?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              body?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
        askLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  roles?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        roles?:
          | T
          | {
              party?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              promise?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              body?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              objection?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              answer?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              screen?: T;
              id?: T;
            };
        sharedPromises?:
          | T
          | {
              promise?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
      };
  innerCycle?:
    | T
    | {
        shows?: T;
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        lead?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        cycles?:
          | T
          | {
              party?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              note?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              reviewers?:
                | T
                | {
                    reviewer?:
                      | T
                      | {
                          ar?: T;
                          en?: T;
                        };
                    id?: T;
                  };
              crosses?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
        privateTag?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        crossesLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        reviewAgain?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        staysInside?:
          | T
          | {
              label?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              emphasis?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
            };
        crossesOut?:
          | T
          | {
              label?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              emphasis?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "closing-section_select".
 */
export interface ClosingSectionSelect<T extends boolean = true> {
  languages?: T;
  closing?:
    | T
    | {
        eyebrow?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        heading?:
          | T
          | {
              ar?: T;
              en?: T;
            };
        steps?:
          | T
          | {
              label?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              text?:
                | T
                | {
                    ar?: T;
                    en?: T;
                  };
              id?: T;
            };
        moreLabel?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "screen-mocks_select".
 */
export interface ScreenMocksSelect<T extends boolean = true> {
  languages?: T;
  correspondence?:
    | T
    | {
        picture?: T;
        description?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  kanban?:
    | T
    | {
        picture?: T;
        description?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  dailyReport?:
    | T
    | {
        picture?: T;
        description?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  documents?:
    | T
    | {
        picture?: T;
        description?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  stampedSheet?:
    | T
    | {
        picture?: T;
        description?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  overview?:
    | T
    | {
        picture?: T;
        description?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  approvalsTable?:
    | T
    | {
        picture?: T;
        description?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  submittal?:
    | T
    | {
        picture?: T;
        description?:
          | T
          | {
              ar?: T;
              en?: T;
            };
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}